# Generated by Django 5.1.1 on 2024-09-28 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='phone_images/')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('operating_system', models.CharField(blank=True, max_length=50, null=True)),
                ('storage', models.PositiveIntegerField()),
                ('ram', models.PositiveIntegerField()),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='shop.category')),
            ],
        ),
    ]
